name: "Reminders"
description: "Native Flutter reminders KPA application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/KasperskySansText-Regular.woff2
    - assets/fonts/KasperskySansText-Medium.woff2
    - assets/fonts/KasperskySansText-SemiBold.woff2

  fonts:
    - family: Kaspersky Sans Text
      fonts:
        - asset: assets/fonts/KasperskySansText-Regular.woff2
          weight: 400
        - asset: assets/fonts/KasperskySansText-Medium.woff2
          weight: 500
        - asset: assets/fonts/KasperskySansText-SemiBold.woff2
          weight: 600
