name: "Launcher"
description: "Native Flutter launcher application for KasperskyOS Mobile."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/wallpaper.png
    - assets/icons/browser.png
    - assets/icons/calculator.png
    - assets/icons/calendar.png
    - assets/icons/camera.png
    - assets/icons/clock.png
    - assets/icons/compass.png
    - assets/icons/contacts.png
    - assets/icons/dictaphone.png
    - assets/icons/files.png
    - assets/icons/gallery.png
    - assets/icons/mail.png
    - assets/icons/maps.png
    - assets/icons/messenger.png
    - assets/icons/my_office.png
    - assets/icons/notes.png
    - assets/icons/phone.png
    - assets/icons/settings.png
    - assets/icons/sms.png
    - assets/icons/video.png
    - assets/icons/vpn.png
    - assets/icons/weather.png
    - assets/screens/camera.png
    - assets/screens/files.png
    - assets/screens/gallery.png
    - assets/screens/phone.png
    - assets/screens/settings.png
    - assets/screens/weather.png
    - assets/fonts/text_regular.woff2
    - assets/fonts/text_medium.woff2
    - assets/fonts/text_semibold.woff2
    - assets/fonts/clock_regular.otf

  fonts:
    - family: Kaspersky Sans Text
      fonts:
        - asset: assets/fonts/text_regular.woff2
          weight: 400
        - asset: assets/fonts/text_medium.woff2
          weight: 500
        - asset: assets/fonts/text_semibold.woff2
          weight: 600
    - family: Kaspersky Sans Clock
      fonts:
        - asset: assets/fonts/clock_regular.otf
          weight: 400
