import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const iconsDirectory = path.resolve(__dirname, '../src/assets/icons');
const outputDirectory = path.resolve(__dirname, '../src/generated');
const outputFile = path.join(outputDirectory, 'icons.ts');
const ID_PREFIX_TOKEN = '__ICON_ID__';

function extractViewBox(svgSource, filePath) {
	const viewBoxMatch = svgSource.match(/\sviewBox=(['"])(.*?)\1/i);
	if (viewBoxMatch) {
		return viewBoxMatch[2];
	}

	const widthMatch = svgSource.match(/\swidth=(['"])(.*?)\1/i);
	const heightMatch = svgSource.match(/\sheight=(['"])(.*?)\1/i);

	if (!widthMatch || !heightMatch) {
		throw new Error(`Unable to resolve viewBox for ${filePath}`);
	}

	const width = Number.parseFloat(widthMatch[2]);
	const height = Number.parseFloat(heightMatch[2]);

	if (!Number.isFinite(width) || !Number.isFinite(height)) {
		throw new Error(`Unable to resolve numeric width/height for ${filePath}`);
	}

	return `0 0 ${width} ${height}`;
}

function replacePaintAttributes(markup) {
	return markup.replace(/\s(fill|stroke)=(['"])(.*?)\2/gi, (fullMatch, attribute, quote, value) => {
		const normalizedValue = value.trim().toLowerCase();

		if (
			normalizedValue === 'none' ||
			normalizedValue === 'currentcolor' ||
			normalizedValue.startsWith('url(')
		) {
			return fullMatch;
		}

		return ` ${attribute}=${quote}currentColor${quote}`;
	});
}

function prefixDefinitionIds(markup) {
	const ids = [...markup.matchAll(/\sid=(['"])([^'"]+)\1/gi)].map((match) => match[2]);

	if (ids.length === 0) {
		return markup;
	}

	let nextMarkup = markup;

	for (const id of new Set(ids)) {
		const prefixedId = `${ID_PREFIX_TOKEN}${id}`;
		nextMarkup = nextMarkup.replaceAll(`id="${id}"`, `id="${prefixedId}"`);
		nextMarkup = nextMarkup.replaceAll(`id='${id}'`, `id='${prefixedId}'`);
		nextMarkup = nextMarkup.replaceAll(`url(#${id})`, `url(#${prefixedId})`);
		nextMarkup = nextMarkup.replaceAll(`href="#${id}"`, `href="#${prefixedId}"`);
		nextMarkup = nextMarkup.replaceAll(`href='#${id}'`, `href='#${prefixedId}'`);
		nextMarkup = nextMarkup.replaceAll(`xlink:href="#${id}"`, `xlink:href="#${prefixedId}"`);
		nextMarkup = nextMarkup.replaceAll(`xlink:href='#${id}'`, `xlink:href='#${prefixedId}'`);
	}

	return nextMarkup;
}

function transformSvg(svgSource, filePath) {
	const svgMatch = svgSource
		.replace(/\r\n/g, '\n')
		.trim()
		.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/i);

	if (!svgMatch) {
		throw new Error(`Unable to parse ${filePath}`);
	}

	const viewBox = extractViewBox(svgSource, filePath);
	const body = prefixDefinitionIds(replacePaintAttributes(svgMatch[1].trim()));

	return {
		viewBox,
		body,
	};
}

const iconEntries = readdirSync(iconsDirectory)
	.filter((fileName) => fileName.toLowerCase().endsWith('.svg'))
	.sort((left, right) => left.localeCompare(right))
	.map((fileName) => {
		const filePath = path.join(iconsDirectory, fileName);
		const iconName = fileName.replace(/\.svg$/i, '');
		const source = readFileSync(filePath, 'utf8');
		const definition = transformSvg(source, filePath);

		return [iconName, definition];
	});

const output = `/* eslint-disable */
// Auto-generated by scripts/build-icons.mjs. Do not edit manually.

export type IconDefinition = {
	viewBox: string;
	body: string;
};

export const iconDefinitions = ${JSON.stringify(Object.fromEntries(iconEntries), null, '\t')} as const satisfies Record<string, IconDefinition>;

export const iconNames = Object.keys(iconDefinitions).sort();

export const iconIdPrefixToken = ${JSON.stringify(ID_PREFIX_TOKEN)};
`;

mkdirSync(outputDirectory, { recursive: true });
writeFileSync(outputFile, output);
