import Photos from "@/components/Photos";
import Photo from "@/components/Photo";
import ButtonIcon from "@/components/Buttonicon";
import Signal503 from "@/components/Signal503";
import Wifil503 from "@/components/Wifil503";
import Navbar from "@/components/Navbar";
import "@/styles/Frame2088158933.css";
const Frame2088158933 = () => {
    return (
        <div className="scroll-container">
            <div id="2088_158933" className="Pixso-frame-2088_158933">
                <div id="2088_158934" className="Pixso-frame-2088_158934">
                    <div className="frame-content-2088_158934">
                        <div
                            id="2088_158935"
                            className="Pixso-frame-2088_158935"
                        >
                            <div className="frame-content-2088_158935">
                                <div
                                    id="2088_158936"
                                    className="Pixso-rectangle-2088_158936"
                                ></div>
                                <div
                                    id="2088_158937"
                                    className="Pixso-frame-2088_158937"
                                >
                                    <p
                                        id="2088_158938"
                                        className="Pixso-paragraph-2088_158938 text-semibold32-981_10844"
                                    >
                                        {"Путешествия"}
                                    </p>
                                    <p
                                        id="2088_158939"
                                        className="Pixso-paragraph-2088_158939 text-regular12-62_2583"
                                    >
                                        {"1 235 обьекта"}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <Photos
                            id="2088_158940"
                            className="Pixso-instance-2088_158940"
                            slot_431_165285={
                                <div
                                    id="2301_148262"
                                    className="Pixso-instance-2301_148262"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></div>
                            }
                            slot_431_165317={
                                <Photo
                                    id="2301_148337"
                                    className="Pixso-instance-2301_148337"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165316={
                                <Photo
                                    id="2301_148335"
                                    className="Pixso-instance-2301_148335"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165315={
                                <Photo
                                    id="2301_148333"
                                    className="Pixso-instance-2301_148333"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165314={
                                <Photo
                                    id="2301_148331"
                                    className="Pixso-instance-2301_148331"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165313={
                                <Photo
                                    id="2301_148329"
                                    className="Pixso-instance-2301_148329"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165312={
                                <Photo
                                    id="2301_148327"
                                    className="Pixso-instance-2301_148327"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165311={
                                <Photo
                                    id="2301_148325"
                                    className="Pixso-instance-2301_148325"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165310={
                                <Photo
                                    id="2301_148323"
                                    className="Pixso-instance-2301_148323"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165309={
                                <Photo
                                    id="2301_148321"
                                    className="Pixso-instance-2301_148321"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165308={
                                <Photo
                                    id="2301_148319"
                                    className="Pixso-instance-2301_148319"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165307={
                                <Photo
                                    id="2301_148317"
                                    className="Pixso-instance-2301_148317"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165306={
                                <Photo
                                    id="2301_148315"
                                    className="Pixso-instance-2301_148315"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165305={
                                <Photo
                                    id="2301_148313"
                                    className="Pixso-instance-2301_148313"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165304={
                                <Photo
                                    id="2301_148311"
                                    className="Pixso-instance-2301_148311"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165303={
                                <Photo
                                    id="2301_148309"
                                    className="Pixso-instance-2301_148309"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165302={
                                <Photo
                                    id="2301_148307"
                                    className="Pixso-instance-2301_148307"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165301={
                                <Photo
                                    id="2301_148305"
                                    className="Pixso-instance-2301_148305"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165300={
                                <Photo
                                    id="2301_148303"
                                    className="Pixso-instance-2301_148303"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165299={
                                <Photo
                                    id="2301_148301"
                                    className="Pixso-instance-2301_148301"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165298={
                                <Photo
                                    id="2301_148299"
                                    className="Pixso-instance-2301_148299"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165297={
                                <Photo
                                    id="2301_148294"
                                    className="Pixso-instance-2301_148294"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="yes"
                                    slot_431_165337={
                                        <div
                                            id="2301_148296"
                                            className="Pixso-instance-2301_148296"
                                            Property1="light"
                                        ></div>
                                    }
                                ></Photo>
                            }
                            slot_431_165296={
                                <Photo
                                    id="2301_148292"
                                    className="Pixso-instance-2301_148292"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165295={
                                <Photo
                                    id="2301_148290"
                                    className="Pixso-instance-2301_148290"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165294={
                                <Photo
                                    id="2301_148288"
                                    className="Pixso-instance-2301_148288"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165293={
                                <Photo
                                    id="2301_148286"
                                    className="Pixso-instance-2301_148286"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165292={
                                <Photo
                                    id="2301_148284"
                                    className="Pixso-instance-2301_148284"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165291={
                                <Photo
                                    id="2301_148282"
                                    className="Pixso-instance-2301_148282"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165289={
                                <Photo
                                    id="2301_148274"
                                    className="Pixso-instance-2301_148274"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165287={
                                <Photo
                                    id="2301_148266"
                                    className="Pixso-instance-2301_148266"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165286={
                                <Photo
                                    id="2301_148264"
                                    className="Pixso-instance-2301_148264"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165284={
                                <Photo
                                    id="2301_148260"
                                    className="Pixso-instance-2301_148260"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165283={
                                <Photo
                                    id="2301_148258"
                                    className="Pixso-instance-2301_148258"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165282={
                                <Photo
                                    id="2301_148256"
                                    className="Pixso-instance-2301_148256"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165281={
                                <Photo
                                    id="2301_148254"
                                    className="Pixso-instance-2301_148254"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165280={
                                <Photo
                                    id="2301_148252"
                                    className="Pixso-instance-2301_148252"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165279={
                                <Photo
                                    id="2301_148250"
                                    className="Pixso-instance-2301_148250"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165276={
                                <Photo
                                    id="2301_148236"
                                    className="Pixso-instance-2301_148236"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165275={
                                <Photo
                                    id="2301_148234"
                                    className="Pixso-instance-2301_148234"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165274={
                                <Photo
                                    id="2301_148232"
                                    className="Pixso-instance-2301_148232"
                                    selected="no"
                                    favourite="no"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165277={
                                <Photo
                                    id="431_165277"
                                    className="Pixso-instance-431_165277"
                                    selected="no"
                                    favourite="yes"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165278={
                                <Photo
                                    id="431_165278"
                                    className="Pixso-instance-431_165278"
                                    selected="no"
                                    favourite="yes"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165288={
                                <Photo
                                    id="431_165288"
                                    className="Pixso-instance-431_165288"
                                    selected="no"
                                    favourite="yes"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                            slot_431_165290={
                                <Photo
                                    id="431_165290"
                                    className="Pixso-instance-431_165290"
                                    selected="no"
                                    favourite="yes"
                                    deleted="no"
                                    notavailable="no"
                                ></Photo>
                            }
                        ></Photos>
                    </div>
                </div>
                <div
                    id="2088_159095"
                    className="Pixso-rectangle-2088_159095"
                ></div>
                <div
                    id="2088_159048"
                    className="Pixso-rectangle-2088_159048"
                ></div>
                <div id="2088_159049" className="Pixso-frame-2088_159049">
                    <div className="frame-content-2088_159049">
                        <div
                            id="2088_159050"
                            className="Pixso-frame-2088_159050"
                        >
                            <div className="frame-content-2088_159050">
                                <ButtonIcon
                                    id="2105_71"
                                    className="Pixso-instance-2105_71"
                                    type="primary"
                                    size="44"
                                    slot_767_155146={
                                        <div
                                            id="767_155146"
                                            className="Pixso-instance-767_155146"
                                        ></div>
                                    }
                                ></ButtonIcon>
                                <ButtonIcon
                                    id="2105_104"
                                    className="Pixso-instance-2105_104"
                                    type="primary"
                                    size="44"
                                    slot_767_155146={
                                        <div
                                            id="767_155146"
                                            className="Pixso-instance-767_155146"
                                        ></div>
                                    }
                                ></ButtonIcon>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="2088_159770" className="Pixso-frame-2088_159770">
                    <div className="frame-content-2088_159770">
                        <div id="2105_186" className="Pixso-frame-2105_186">
                            <div id="2105_187" className="Pixso-frame-2105_187">
                                <div
                                    id="2105_188"
                                    className="Pixso-vector-2105_188"
                                ></div>
                                <div
                                    id="2105_189"
                                    className="Pixso-vector-2105_189"
                                ></div>
                            </div>
                            <div id="2105_196" className="Pixso-frame-2105_196">
                                <p
                                    id="2105_197"
                                    className="Pixso-paragraph-2105_197 fill-lightcontentprimary-62_2618-paragraph text-medium14-204_426"
                                >
                                    {"13:52"}
                                </p>
                            </div>
                        </div>
                        <div
                            id="2088_159776"
                            className="Pixso-frame-2088_159776"
                        >
                            <div className="frame-content-2088_159776">
                                <Signal503
                                    id="2088_159777"
                                    className="Pixso-instance-2088_159777"
                                ></Signal503>
                                <Wifil503
                                    id="2088_159778"
                                    className="Pixso-instance-2088_159778"
                                ></Wifil503>
                                <div
                                    id="2088_159779"
                                    className="Pixso-vector-2088_159779"
                                ></div>
                            </div>
                        </div>
                    </div>
                </div>
                <Navbar
                    id="2088_159086"
                    className="Pixso-instance-2088_159086"
                    back="back"
                    darkmode="false"
                    slot_431_164036={
                        <div
                            id="2301_78838"
                            className="Pixso-vector-2301_78838"
                        ></div>
                    }
                    slot_431_164037={
                        <div
                            id="2301_78835"
                            className="Pixso-vector-2301_78835"
                        ></div>
                    }
                ></Navbar>
            </div>
        </div>
    );
};
export default Frame2088158933;
