import CellTitle0 from "@/components/Celltitle0";
import CellTitle from "@/components/Celltitle";
import ButtonIcon from "@/components/Buttonicon";
import Signal503 from "@/components/Signal503";
import Wifil503 from "@/components/Wifil503";
import Navbar from "@/components/Navbar";
import NewAppbar from "@/components/Newappbar";
import Foldergallery from "@/components/Foldergallery";
import "@/styles/Frame2027161555.css";
const Frame2027161555 = () => {
    return (
        <div className="scroll-container">
            <div id="2027_161555" className="Pixso-frame-2027_161555">
                <div id="2027_161556" className="Pixso-frame-2027_161556">
                    <div className="frame-content-2027_161556">
                        <div
                            id="2289_158896"
                            className="Pixso-frame-2289_158896"
                        >
                            <div
                                id="2289_158897"
                                className="Pixso-frame-2289_158897"
                            >
                                <div
                                    id="2289_158898"
                                    className="Pixso-rectangle-2289_158898"
                                ></div>
                                <div
                                    id="2289_158899"
                                    className="Pixso-rectangle-2289_158899"
                                ></div>
                                <p
                                    id="2289_158900"
                                    className="Pixso-paragraph-2289_158900"
                                >
                                    {"Избранное"}
                                </p>
                            </div>
                            <div
                                id="2289_158901"
                                className="Pixso-frame-2289_158901"
                            >
                                <div
                                    id="2289_158902"
                                    className="Pixso-rectangle-2289_158902"
                                ></div>
                                <div
                                    id="2289_158903"
                                    className="Pixso-vector-2289_158903"
                                ></div>
                                <p
                                    id="2289_158904"
                                    className="Pixso-paragraph-2289_158904"
                                >
                                    {"Избранное"}
                                </p>
                            </div>
                            <div
                                id="2289_158905"
                                className="Pixso-frame-2289_158905"
                            >
                                <div
                                    id="2289_158906"
                                    className="Pixso-rectangle-2289_158906"
                                ></div>
                                <div
                                    id="2289_158907"
                                    className="Pixso-rectangle-2289_158907"
                                ></div>
                                <p
                                    id="2289_158908"
                                    className="Pixso-paragraph-2289_158908 text-semibold20-1116_1447"
                                >
                                    {"Избранное"}
                                </p>
                            </div>
                        </div>
                        <div
                            id="2027_161567"
                            className="Pixso-frame-2027_161567"
                        >
                            <div className="frame-content-2027_161567">
                                <CellTitle0
                                    id="2027_161568"
                                    className="Pixso-instance-2027_161568"
                                    text_5143_0={`Мои альбомы`}
                                    dark_mode="no"
                                    left="no"
                                    right="icons"
                                    padding="no"
                                    content="title"
                                    __pixsoClassOverrides={{
                                        ["overrideClass_1981_159057"]: [
                                            "text-semibold20-1116_1447"
                                        ]
                                    }}
                                    slot_1981_159058={
                                        <div
                                            id="2301_122147"
                                            className="Pixso-instance-2301_122147"
                                            count="1"
                                            dark_mode="false"
                                            gap="small"
                                        ></div>
                                    }
                                    slot_1981_159057={
                                        <p
                                            id="2301_122146"
                                            className="Pixso-paragraph-2301_122146 text-semibold20-1116_1447"
                                        >
                                            {"Мои альбомы"}
                                        </p>
                                    }
                                ></CellTitle0>
                                <div
                                    id="2027_161573"
                                    className="Pixso-frame-2027_161573"
                                >
                                    <div className="frame-content-2027_161573">
                                        <div
                                            id="2027_161574"
                                            className="Pixso-frame-2027_161574"
                                        >
                                            <div
                                                id="2027_161575"
                                                className="Pixso-rectangle-2027_161575"
                                            ></div>
                                            <div
                                                id="2027_161576"
                                                className="Pixso-rectangle-2027_161576"
                                            ></div>
                                            <div
                                                id="2027_161577"
                                                className="Pixso-frame-2027_161577"
                                            >
                                                <p
                                                    id="2027_161578"
                                                    className="Pixso-paragraph-2027_161578 text-medium16-981_10378"
                                                >
                                                    {"Делишки"}
                                                </p>
                                                <p
                                                    id="2027_161579"
                                                    className="Pixso-paragraph-2027_161579 text-regular12-62_2583"
                                                >
                                                    {"142 обьекта"}
                                                </p>
                                            </div>
                                        </div>
                                        <div
                                            id="2027_161580"
                                            className="Pixso-frame-2027_161580"
                                        >
                                            <div
                                                id="2027_161581"
                                                className="Pixso-vector-2027_161581"
                                            ></div>
                                            <div
                                                id="2027_161582"
                                                className="Pixso-rectangle-2027_161582"
                                            ></div>
                                            <div
                                                id="2027_161583"
                                                className="Pixso-frame-2027_161583"
                                            >
                                                <p
                                                    id="2027_161584"
                                                    className="Pixso-paragraph-2027_161584 text-medium16-981_10378"
                                                >
                                                    {"Коллеги"}
                                                </p>
                                                <p
                                                    id="2027_161585"
                                                    className="Pixso-paragraph-2027_161585 text-regular12-62_2583"
                                                >
                                                    {"54 обьекта"}
                                                </p>
                                            </div>
                                        </div>
                                        <div
                                            id="2027_161586"
                                            className="Pixso-frame-2027_161586"
                                        >
                                            <div
                                                id="2027_161587"
                                                className="Pixso-vector-2027_161587"
                                            ></div>
                                            <div
                                                id="2027_161588"
                                                className="Pixso-rectangle-2027_161588"
                                            ></div>
                                            <div
                                                id="2027_161589"
                                                className="Pixso-frame-2027_161589"
                                            >
                                                <p
                                                    id="2027_161590"
                                                    className="Pixso-paragraph-2027_161590 text-medium16-981_10378"
                                                >
                                                    {"Коллеги"}
                                                </p>
                                                <p
                                                    id="2027_161591"
                                                    className="Pixso-paragraph-2027_161591 text-regular12-62_2583"
                                                >
                                                    {"54 обьекта"}
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div
                            id="2027_161592"
                            className="Pixso-frame-2027_161592"
                        >
                            <div className="frame-content-2027_161592">
                                <CellTitle0
                                    id="2027_161593"
                                    className="Pixso-instance-2027_161593"
                                    text_5143_0={`Категории`}
                                    dark_mode="no"
                                    left="no"
                                    right="icons"
                                    padding="no"
                                    content="title"
                                    __pixsoClassOverrides={{
                                        ["overrideClass_1981_159057"]: [
                                            "text-semibold20-1116_1447"
                                        ]
                                    }}
                                    slot_1981_159058={
                                        <div
                                            id="2301_122139"
                                            className="Pixso-instance-2301_122139"
                                            count="1"
                                            dark_mode="false"
                                            gap="small"
                                        ></div>
                                    }
                                    slot_1981_159057={
                                        <p
                                            id="2301_122138"
                                            className="Pixso-paragraph-2301_122138 text-semibold20-1116_1447"
                                        >
                                            {"Категории"}
                                        </p>
                                    }
                                ></CellTitle0>
                                <div
                                    id="2027_161598"
                                    className="Pixso-frame-2027_161598"
                                >
                                    <CellTitle
                                        id="2027_161599"
                                        className="Pixso-instance-2027_161599"
                                        text_5143_0={`Фото`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80684"
                                                className="Pixso-instance-2301_80684"
                                                is_outline="true"
                                            ></div>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="2301_80687"
                                                className="Pixso-paragraph-2301_80687 text-regular14-504_2349"
                                            >
                                                {"1 124"}
                                            </p>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80686"
                                                className="Pixso-paragraph-2301_80686 text-medium16-1004_170482"
                                            >
                                                {"Фото"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161604"
                                        className="Pixso-instance-2027_161604"
                                        text_5143_0={`Видео`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80576"
                                                className="Pixso-instance-2301_80576"
                                                is_outline="true"
                                            ></div>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="2301_80579"
                                                className="Pixso-paragraph-2301_80579 text-regular14-504_2349"
                                            >
                                                {"421"}
                                            </p>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80578"
                                                className="Pixso-paragraph-2301_80578 text-medium16-1004_170482"
                                            >
                                                {"Видео"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161609"
                                        className="Pixso-instance-2027_161609"
                                        text_5143_0={`Скриншоты`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80688"
                                                className="Pixso-instance-2301_80688"
                                            ></div>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="2301_80691"
                                                className="Pixso-paragraph-2301_80691 text-regular14-504_2349"
                                            >
                                                {"25"}
                                            </p>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80690"
                                                className="Pixso-paragraph-2301_80690 text-medium16-1004_170482"
                                            >
                                                {"Скриншоты"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161614"
                                        className="Pixso-instance-2027_161614"
                                        text_5143_0={`Записи экрана`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80840"
                                                className="Pixso-instance-2301_80840"
                                            ></div>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="2301_80843"
                                                className="Pixso-paragraph-2301_80843 text-regular14-504_2349"
                                            >
                                                {"5"}
                                            </p>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80842"
                                                className="Pixso-paragraph-2301_80842 text-medium16-1004_170482"
                                            >
                                                {"Записи экрана"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161619"
                                        className="Pixso-instance-2027_161619"
                                        text_5143_0={`Загрузки`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80580"
                                                className="Pixso-instance-2301_80580"
                                            ></div>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="2301_80583"
                                                className="Pixso-paragraph-2301_80583 text-regular14-504_2349"
                                            >
                                                {"159"}
                                            </p>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80582"
                                                className="Pixso-paragraph-2301_80582 text-medium16-1004_170482"
                                            >
                                                {"Загрузки"}
                                            </p>
                                        }
                                    ></CellTitle>
                                </div>
                            </div>
                        </div>
                        <div
                            id="2027_161624"
                            className="Pixso-frame-2027_161624"
                        >
                            <div className="frame-content-2027_161624">
                                <CellTitle0
                                    id="2027_161625"
                                    className="Pixso-instance-2027_161625"
                                    text_5143_0={`Другое`}
                                    dark_mode="no"
                                    left="no"
                                    right="icons"
                                    padding="no"
                                    content="title"
                                    __pixsoClassOverrides={{
                                        ["overrideClass_1981_159057"]: [
                                            "text-semibold20-1116_1447"
                                        ]
                                    }}
                                    slot_1981_159057={
                                        <p
                                            id="2301_122142"
                                            className="Pixso-paragraph-2301_122142 text-semibold20-1116_1447"
                                        >
                                            {"Другое"}
                                        </p>
                                    }
                                ></CellTitle0>
                                <div
                                    id="2027_161630"
                                    className="Pixso-frame-2027_161630"
                                >
                                    <CellTitle
                                        id="2027_161631"
                                        className="Pixso-instance-2027_161631"
                                        text_5143_0={`Корзина`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80680"
                                                className="Pixso-instance-2301_80680"
                                                is_outline="true"
                                            ></div>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80682"
                                                className="Pixso-paragraph-2301_80682 text-medium16-1004_170482"
                                            >
                                                {"Корзина"}
                                            </p>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="1004_170612"
                                                className="Pixso-paragraph-1004_170612 text-regular14-504_2349"
                                            >
                                                {"25"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161636"
                                        className="Pixso-instance-2027_161636"
                                        text_5143_0={`Скрытое`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80584"
                                                className="Pixso-instance-2301_80584"
                                                is_outline="true"
                                            ></div>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80586"
                                                className="Pixso-paragraph-2301_80586 text-medium16-1004_170482"
                                            >
                                                {"Скрытое"}
                                            </p>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="1004_170612"
                                                className="Pixso-paragraph-1004_170612 text-regular14-504_2349"
                                            >
                                                {"25"}
                                            </p>
                                        }
                                    ></CellTitle>
                                    <CellTitle
                                        id="2027_161641"
                                        className="Pixso-instance-2027_161641"
                                        text_5143_0={`Безопасная папка`}
                                        dark_mode="no"
                                        left="icon"
                                        right="text"
                                        padding="yes"
                                        content="title"
                                        slot_1004_170610={
                                            <div
                                                id="2301_80832"
                                                className="Pixso-instance-2301_80832"
                                                is_outline="true"
                                            ></div>
                                        }
                                        slot_1004_170611={
                                            <p
                                                id="2301_80834"
                                                className="Pixso-paragraph-2301_80834 text-medium16-1004_170482"
                                            >
                                                {"Безопасная папка"}
                                            </p>
                                        }
                                        slot_1004_170612={
                                            <p
                                                id="1004_170612"
                                                className="Pixso-paragraph-1004_170612 text-regular14-504_2349"
                                            >
                                                {"25"}
                                            </p>
                                        }
                                    ></CellTitle>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div
                    id="2027_161646"
                    className="Pixso-rectangle-2027_161646"
                ></div>
                <div
                    id="2027_161647"
                    className="Pixso-rectangle-2027_161647"
                ></div>
                <div id="2027_161648" className="Pixso-frame-2027_161648">
                    <div className="frame-content-2027_161648">
                        <div
                            id="2027_161649"
                            className="Pixso-frame-2027_161649"
                        >
                            <div className="frame-content-2027_161649">
                                <p
                                    id="2027_161650"
                                    className="Pixso-paragraph-2027_161650 text-semibold32-78_16432"
                                >
                                    {"Альбомы"}
                                </p>
                                <div
                                    id="2105_167"
                                    className="Pixso-frame-2105_167"
                                >
                                    <ButtonIcon
                                        id="2105_168"
                                        className="Pixso-instance-2105_168"
                                        type="primary"
                                        size="44"
                                        slot_767_155146={
                                            <div
                                                id="767_155146"
                                                className="Pixso-instance-767_155146"
                                            ></div>
                                        }
                                    ></ButtonIcon>
                                    <ButtonIcon
                                        id="2105_169"
                                        className="Pixso-instance-2105_169"
                                        type="primary"
                                        size="44"
                                        slot_767_155146={
                                            <div
                                                id="767_155146"
                                                className="Pixso-instance-767_155146"
                                            ></div>
                                        }
                                    ></ButtonIcon>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="2088_159665" className="Pixso-frame-2088_159665">
                    <div className="frame-content-2088_159665">
                        <div
                            id="2088_159666"
                            className="Pixso-frame-2088_159666"
                        >
                            <div
                                id="2102_1422"
                                className="Pixso-frame-2102_1422"
                            >
                                <div
                                    id="2102_1423"
                                    className="Pixso-vector-2102_1423"
                                ></div>
                                <div
                                    id="2102_1424"
                                    className="Pixso-vector-2102_1424"
                                ></div>
                            </div>
                            <div
                                id="2088_159669"
                                className="Pixso-frame-2088_159669"
                            >
                                <p
                                    id="2088_159670"
                                    className="Pixso-paragraph-2088_159670 fill-lightcontentprimary-62_2618-paragraph text-medium14-204_426"
                                >
                                    {"13:52"}
                                </p>
                            </div>
                        </div>
                        <div
                            id="2088_159671"
                            className="Pixso-frame-2088_159671"
                        >
                            <div className="frame-content-2088_159671">
                                <Signal503
                                    id="2088_159672"
                                    className="Pixso-instance-2088_159672"
                                ></Signal503>
                                <Wifil503
                                    id="2088_159673"
                                    className="Pixso-instance-2088_159673"
                                ></Wifil503>
                                <div
                                    id="2088_159674"
                                    className="Pixso-vector-2088_159674"
                                ></div>
                            </div>
                        </div>
                    </div>
                </div>
                <Navbar
                    id="2027_161680"
                    className="Pixso-instance-2027_161680"
                    back="back"
                    darkmode="false"
                    slot_431_164036={
                        <div
                            id="2301_78902"
                            className="Pixso-vector-2301_78902"
                        ></div>
                    }
                    slot_431_164037={
                        <div
                            id="2301_78899"
                            className="Pixso-vector-2301_78899"
                        ></div>
                    }
                ></Navbar>
                <NewAppbar
                    id="2027_161689"
                    className="Pixso-instance-2027_161689"
                    slot_445_139139={
                        <div
                            id="2301_80076"
                            className="Pixso-instance-2301_80076"
                        ></div>
                    }
                    slot_445_139143={
                        <p
                            id="2301_80087"
                            className="Pixso-paragraph-2301_80087"
                        >
                            {"Альбомы"}
                        </p>
                    }
                    slot_445_139142={
                        <Foldergallery
                            id="2301_80082"
                            className="Pixso-instance-2301_80082"
                            slot_1981_158338={
                                <div
                                    id="2301_80083"
                                    className="Pixso-instance-2301_80083"
                                    stroke="yes"
                                    image="no"
                                ></div>
                            }
                        ></Foldergallery>
                    }
                    slot_445_139140={
                        <p
                            id="2301_80080"
                            className="Pixso-paragraph-2301_80080"
                        >
                            {"Альбомы"}
                        </p>
                    }
                    slot_445_139136={
                        <div
                            id="445_139136"
                            className="Pixso-instance-445_139136"
                        ></div>
                    }
                    slot_445_139137={
                        <p
                            id="445_139137"
                            className="Pixso-paragraph-445_139137"
                        >
                            {"Все фото"}
                        </p>
                    }
                ></NewAppbar>
            </div>
        </div>
    );
};
export default Frame2027161555;
